// File: frontend/main.jsx

// ✅ Global CSS imports
import "mapbox-gl/dist/mapbox-gl.css"; // Mapbox styles
import "./index.css";                  // Tailwind base (generated by Vite)

// ✅ React core
import React from "react";
import ReactDOM from "react-dom/client";

// ✅ App entry
import App from "./studio/App.jsx";

// ✅ Render tree
ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
